### ISSUE TITLE
Homepage QA feedback

### ISSUE THREAD

**Issue by jquispe-oddball** [department-of-veterans-affairs/va.gov-team#103890]
Fix frontend issues from HP QA, see [comment](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103502#issuecomment-2680246262) for screenshots

- [x] Fix font weight, see figma
- [x] Header should be #FFF, not #F0F0F0
- [x] Hero background should have rounded corners on desktop/mobile
- [x] On "Help us improve your portal experience", there should be more padding on top of header and under text 
- [x] **Not related to HP**: Header navigation is overlapping the logo on 320px, see screenshot. Both auth/unauth experience have issues
- [x] Test program email overlaps outside the alert box on 320px
- [x] All links that have "(opens in a new tab)" have a small period mark at the end, this should not be there.
- [x] ~~Info icon not aligned on top of "Get early copy", see screenshot~~ Bug in design system
- [x] The Note: under "What the portal can do" should be bold
- [x] "Help us improve..." image sizing
- [x] Footer width responsive issues

**Comment by jquispe-oddball** [comment]
@candilemoine I will go ahead and close the [HP](https://github.com/department-of-veterans-affairs/va.gov-team/issues/103502) ticket since I opened up this bug ticket.

cc: @eheintzelman @seipeljl @lauraparadis-nava

**Comment by candilemoine** [comment]
Thank you! Any v0 bugs and fixes take priority over these.

**Comment by jquispe-oddball** [comment]
Note: icon alignment issue with the banner is a known bug from the design system. There is a [ticket](https://github.com/department-of-veterans-affairs/vets-design-system-documentation/issues/3881) to fix this

**Comment by jquispe-oddball** [comment]
This is on staging.

Font weight fixed with `-webkit-font-smoothing: antialiased;`
Header navigation fixed on small devices, hero background has rounded corners, see screenshot below.
<img width="1372" alt="Image" src="https://github.com/user-attachments/assets/17ba9b33-a7dd-47eb-aea4-52e2bb07625d" />

Header text is #FFF, see screenshot:
<img width="1363" alt="Image" src="https://github.com/user-attachments/assets/dd325ef1-3dea-4065-9472-aa60f339f766" />

Test program email overlaps outside the alert box on 320px
<img width="622" alt="Image" src="https://github.com/user-attachments/assets/c41f450f-8881-4e2e-9cdc-39c26c697a6e" />

On "Help us improve your portal experience", there should be more padding on top of header and under text
"Help us improve..." image sizing
<img width="1448" alt="Image" src="https://github.com/user-attachments/assets/27feba8a-5ea5-40ac-be46-e09c7145feec" />

The Note: under "What the portal can do" should be bold
<img width="463" alt="Image" src="https://github.com/user-attachments/assets/b7adfd93-2c9e-4d36-819c-2b1a26542dc3" />

Footer width responsive issues, no longer able to recreate the white spacing that was appearing on the sides.

**Comment by candilemoine** [comment]
Noted the bug for the icon alignment and strikethrough within the ticket. I can still see the non-period in the links that open to a new tab. However, we have a separate ticket to remove the `(opens in a new tab)` so I'm less concerned.

Other items are all verified 🎉
