### ISSUE TITLE
Users are unable to update their mailing address on their VA.gov profile. 

### ISSUE THREAD

**Issue by clantosswett** [department-of-veterans-affairs/va.gov-team#1129]
### Status

[UNRESOLVED, RESOLVED]

### Severity Analysis

*Estimate of how critical this bug is*

- `sev 1` 
    - Immediate resolution needed
    - Critical incident
- `sev 2` 
    - Needs a special deploy
    - Needs SME
    - Regression that went uncaught in dev/staging
- `sev 3` 
    - Can go out in a regular deploy but still needs fixed ASAP
    - Can be put into the owning team's backlog and scheduled by PM

### User Impact 

- A growing number of VA.gov users are unable to update their mailing address on their VA.gov profile. This means any mail they might be receiving continues going to the wrong address. 

### Description

- A user with an identity proofed account goes to their profile to update their mailing address and are shown error messages that VA.gov cannot update their address. 

### Steps to Reproduce

I have ~10 examples of this issue happening. I tested using the address from one of the users who submitted an issue. I won't enter the address below because of PII issues but can send that information along if it is needed. 

- Sign into VA.gov account of a user that has been identity proofed on chrome
-Go to VA.gov profile. 
-Click the edit button next to the mailing address
-Delete old mailing address information and enter in new mailing address
-Click save 
-See the attached two error message and see that address is not updated. 

For most of the users who are experiencing this issue, we have confirmed that this issue has been persistent for days, weeks and sometimes months. 

#### Expected Results

- The user's new address should be saved and shown on their profile. 

#### Actual Results

- User receives error messages that their address could not be updated and their old address remains on their profile. 

### Further Details
Please also see excel for the list of issues that have been submitted to us via IRIS.

### Proposed Solution

- *Summary of solution*
- *Link to related tickets*

**Comment by clantosswett** [comment]
[8-20 Mailing Address Update Issues.xlsx](https://github.com/department-of-veterans-affairs/va.gov-team/files/3521335/8-20.Mailing.Address.Update.Issues.xlsx)
![error message address update 1](https://user-images.githubusercontent.com/32465263/63359719-37503180-c33b-11e9-9cb7-8de7a6a93d96.PNG)
![error message address update 2](https://user-images.githubusercontent.com/32465263/63359721-37503180-c33b-11e9-8b8d-fcd709fb8023.PNG)

**Comment by alexpappasoddball** [comment]
@Justin-Pickett I believe this one is for your team.  If so can you relabel accordingly and remove the triage & triage-incident?

**Comment by Justin-Pickett** [comment]
@erikphansen @lihanli can you check this out.

**Comment by lihanli** [comment]
i'll take a look

**Comment by Justin-Pickett** [comment]
@lkoenigsberg will follow up with the Vets360 team on this coming weekly call.

**Comment by lkoenigsberg** [comment]
@clantosswett , can you provide us with a few users who've experienced this?  We are talking with our partners at Vet360 to try and troubleshoot.

**Comment by clantosswett** [comment]
Definitely. I have a whole spreadsheet full of users with this issue. I'll provide to you separately for privacy reasons.

**Comment by lkoenigsberg** [comment]
@lihanli , and news from the Vet360 team?  

Last I heard they might have identified where the problem was.  We also shared an updated spreadsheet with more information last week too.

**Comment by lihanli** [comment]
@lkoenigsberg last thing that happened was on 9/6 i talked with terry bazemore and described the problem and talked about possible solutions, he said he would discuss it with the vet360 team and get back to me on what we should do.

**Comment by lkoenigsberg** [comment]
@lihanli was able to provide some stats the V360 call on 9/6, but they are really looking for a bit deeper analysis if you had it.  Specifically an impact statement in terms of x% of users are unable to complete the action. @clantosswett is working with our analytics team to pull and provide some additional info.

**Comment by lkoenigsberg** [comment]
@clantosswett provided data but need an update from @lihanli on where we stand.

**Comment by lihanli** [comment]
@lkoenigsberg i don't see any recent errors in the logs for the `effectiveStartDate.Past` bug, it looks like vets360 has fixed that issue.
@clantosswett this error should be resolved, can you check with your users if it is?

**Comment by clantosswett** [comment]
Yep. I'll reach out and give an update either way.

**Comment by clantosswett** [comment]
@lihanli  I reached out to 24 users who reported experiencing this issue. So far, two users have responded to my outreach and notified me they are still experiencing the problem and are unable to update their address on VA.gov. Let me know if you want more details about the users and we can figure out the past way to share that information since it is PII.

**Comment by Justin-Pickett** [comment]
We'll hold off on this until we coordinate with Vets360 team regarding validation processes that our team was unaware of at the moment. 

Will follow up after those conversations have taken place.

**Comment by Justin-Pickett** [comment]
Work around has been agreed upon for a course of action for users to update their mailing address when prompted with errors blocking them from completing the intended tasks.

**Comment by lkoenigsberg** [comment]
@clantosswett , any way we can get actual addresses or had you shared that in encrypted msg you provided some time ago to the v360 team?

**Comment by clantosswett** [comment]
I still have actual example addresses that aren't working that I can share. How would you like me to go about doing that?

**Comment by lkoenigsberg** [comment]
Working on getting my encrypted email working but if your in the office tomorrow (Tuesday) I’ll stop by and maybe get a few examples directly from you.

**Comment by clantosswett** [comment]
I'll be in so feel free to stop by whenever!

**Comment by Justin-Pickett** [comment]
I will follow up with @clantosswett to get sample address to validate if this is still an issue.

**Comment by Justin-Pickett** [comment]
@clantosswett can you provide some sample addresses so this can be tested and validated? Let me know the best way that works for you to share these addresses with me.

**Comment by clantosswett** [comment]
@Justin-Pickett Here are a few examples of addresses. I tried to test them on staging to confirm the issue but right now the contact information section of the profile is showing an error message. Not sure what that is about. Let me know if you have any questions. 

2212 S. Chickasaw Trail, Unit 4, Orlando, Fl. 32825 

3954 SW 112th St, Ocala, Florida 34476

1035 Recore Ridge Road, Bessemer City, NC 28016

5965 bridle dr. cumming ga. 30028.

**Comment by Justin-Pickett** [comment]
@clantosswett @erikphansen @lkoenigsberg I was able to test the above addresses on staging and 3 of 4 addresses successfully updated.  

1035 Recore Ridge Road, Bessemer City, NC 28016 - i couldn't get this address to update successfully. @erikphansen can you check into that. I get the error message "We couldn’t save your recent mailing address update. Please try again later."

**Comment by clantosswett** [comment]
@Justin-Pickett thanks for the update. Question. We have 50+ users who have reported the address update issue. Most of them did not share the address they are trying to add. Would it be worth the time or effort to ask for that information? Let me know.

**Comment by Justin-Pickett** [comment]
@clantosswett I think it could be helpful for those addresses to be provided if we can obtain them.

**Comment by clantosswett** [comment]
@Justin-Pickett Okay. It might take a little while to do the outreach but we can certainly ask for them.

**Comment by clantosswett** [comment]
@Justin-Pickett I have a few more addresses that I was able to get from users who confirmed they are still experiencing the issue. I went to try and test these on staging but the address update tool seems to be down. I can go back later to verify but wanted to get these added to the issue. 

1805 E Golden Oak Ct.
Meridian, ID 83646

1226 IMPERIAL BEND DR HOUSTON Texas 77073 

I provided this address before but just wanted to share the user confirms they still can't update it: 1035 RECORE RIDGE ROAD, BESSEMER CITY, NC, 28016

**Comment by Justin-Pickett** [comment]
follow up with @erikphansen to see if he can validate the above addresses. Will bring this up in Vet360 call on this upcoming friday with possible suggestion on how to flag these instances.

**Comment by clantosswett** [comment]
Checking in to see if there are any updates on this issue.

**Comment by clantosswett** [comment]
Here is another address that can't be updated on VA.gov:

Lot 36 Block 4A Camella Baliwag Phase 3 Pagala Baliuag Bulacan, Philippines 3006

**Comment by Justin-Pickett** [comment]
@clantosswett we're making progress but changes aren't final as of yet. I will keep you updated.

**Comment by Justin-Pickett** [comment]
@lihanli can you see what errors are still occuring with this address. 

Lot 36 Block 4A Camella Baliwag Phase 3 Pagala Baliuag Bulacan, Philippines 3006

G CO 2-238 GSAB
TF DRAGON
APO AE 09355

**Comment by lihanli** [comment]
first address returns "ADDRVAL102 SpectrumServiceAddressError No matching results"
second address returns "ADDRVAL112 AddressCouldNotBeFound The Address could not be found"

**Comment by lkoenigsberg** [comment]
Thanks to the [WIP error matrix](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/change-address/address-validation/_ErrorCodesForOverride_DRAFT-WithExamples.xlsx) that @Justin-Pickett is working on we know that the Vet360 responses mean the following.

1. ADDRVAL102 = The Spectrum server is down, address validation is unable to be reached and is not overridable at this time. 
2. ADDRVAL112 = The address was unable to be located or standardized.  This is a 0 confidence address but can be overridden.

We might be able to use these examples to further flush out the matrix to include what the VA.gov user experience is when these errors are thrown and input to further enhancements.  I know @Justin-Pickett is working on that as well.

**Comment by erikphansen** [comment]
@lkoenigsberg @Justin-Pickett I am pretty sure that ADDRVAL112 is not overridable but will be with a VA Profile update due to go out in January

**Comment by lkoenigsberg** [comment]
@erikphansen thanks!  I simply copied and pasted the contents of the error matrix that @Justin-Pickett has been working on so maybe we need to revisit that and verify the "now" vs. "future" expectations.

**Comment by Justin-Pickett** [comment]
Closing this ticket. This will be tackled with the Project for Candidate Address Validation.

**Comment by clantosswett** [comment]
@Justin-Pickett now that this is closed, where should I be adding new addresses that users report aren't working?

**Comment by lkoenigsberg** [comment]
I had suggested to @Justin-Pickett that we collect the addresses in a github doc. This will allow you to add and ya to use them as test cases when we do get the new candidate address system up and running.

**Comment by clantosswett** [comment]
Okay. Just let me know when that github doc is created so I can add them. Thanks!

**Comment by Samara-Strauss** [comment]
We have deleted all comments in this thread that included addresses for PII concerns.
