### ISSUE TITLE
OH: Eligibility Endpoint Returning Incorrect Ineligibility Reason

### ISSUE THREAD

**Issue by simiadebowale** [department-of-veterans-affairs/va.gov-team#126622]
## Description
The Eligibility endpoint is returning an incorrect ineligibility reason for site 668.
When a patient has exceeded the request limit, the API should return the reason `facility-request-limit-exceeded`, but it is currently returning `facility-cs-request-disabled`.

This leads to incorrect messaging and logic handling in the frontend, where the wrong reason determines whether the “Request Appointment” option is displayed.

More details in [thread](https://dsva.slack.com/archives/C062LRFAX7S/p1764090242543629)

---
## Appointment systems affected
Check all appointment systems affected by or relevant to this task

- [ ] vistA
- [ ] HSRM
- [x] CERNER (OH)
- [ ] N/A

## Mobile
Is there a mobile component to this work? If so, is there a mobile ticket made?

- [ ] Yes, ticket link:
- [x] N/a
      
**Steps to Reproduce:**

Call the Relationships endpoint for any patient (e.g., `GET /vaos/v2/relationships?facility_id=668&clinical_service_id=foodAndNutrition&has_availability_before=2026-12-17T23:45:52Z`).

Observe that the hasAvailability field is always false in the response payload, regardless of the provider’s actual scheduling availability.

**Expected Behavior:**
Requests should be disabled in this scenario because Judy is over the request limit at Mann-Grandstaff for Food and Nutrition. The endpoint should return:

"code": "facility-request-limit-exceeded"

This ensures the frontend accurately reflects the user’s scheduling eligibility state.

**Actual Behavior:**

The endpoint currently returns:

"code": "facility-requests-disabled"

This incorrectly indicates that requests are disabled by the facility rather than limited by the request count.

---

**Comment by ala-yna** [comment]
Should be resolved as of 12/4 - need to validate

**Comment by outerpress** [comment]
BE team is working on this in https://issues.mobilehealth.va.gov/browse/VPG-657

**Comment by Jenny-yw** [comment]
Tested on BeardedIPO. This is still only partially resolved for the same reason Peter noted on Dec 15 — the account can still request appointments even with 8 existing Food and Nutrition requests at Mann-Grandstaff, and there's eligibility check for request. @ryanshaw

**Comment by Jenny-yw** [comment]
Validated and good to go!
