### ISSUE TITLE
Wrong hrefs for health_care_region_page

### ISSUE THREAD

**Issue by jhonnyoddball** [department-of-veterans-affairs/va.gov-team#13177]
## Issue Description
There are some hrefs that were not transformed correctly

## Example:
```
<a class="vads-u-margin-bottom--2" href="/pittsburgh-health-care/patient-advocates" id="1bd6700ce1e7badf349c121d5210dabb">

<a class="vads-u-margin-bottom--2" href="entity:node/1e8a72b4-c54c-432e-b53a-ef6a7969f40e" id="1bd6700ce1e7badf349c121d5210dabb">
```

## Example File
`/pittsburgh-health-care/index.html`

## Tasks
- [ ] Figure out why there is a wrong href.
- [ ] Resolve issue, and verify the output matches the GraphQL content build.

**Comment by indytechcook** [comment]
I'm looking at this.

**Comment by indytechcook** [comment]
I have a PR in to fix this: https://github.com/department-of-veterans-affairs/va.gov-cms/pull/2852

**Comment by indytechcook** [comment]
The PR has been merged but not deployed yet.  On next deploy this should be resolved.

**Comment by indytechcook** [comment]
The code has been deployed.  Please retest.

**Comment by jhonnyoddball** [comment]
@indytechcook I just pulled the latest `cms-export` and I still see the discrepancies. Did you do the bulk export after the deploy?

**Comment by indytechcook** [comment]
I see what I expect in the output of `paragraph.98ab52e2-2bc4-44a8-b05a-33024e467572.json`

```
    "field_link": [
        {
            "uri": "\/pittsburgh-health-care\/patient-advocates",
            "title": "Get help from a patient advocate",
            "options": []
        }
    ],
```

Do you know if the url is pulled from somewhere else?

**Comment by indytechcook** [comment]
I also see the following for `node.1e8a72b4-c54c-432e-b53a-ef6a7969f40e.json`

```
    "entityUrl": {
        "breadcrumb": [
            {
                "url": {
                    "path": "\/",
                    "routed": true
                },
                "text": "Home"
            },
            {
                "url": {
                    "path": "\/pittsburgh-health-care",
                    "routed": true
                },
                "text": "VA Pittsburgh health care"
            },
            {
                "url": {
                    "path": "",
                    "routed": true
                },
                "text": "Services and locations"
            },
            {
                "url": {
                    "path": "\/pittsburgh-health-care\/health-services",
                    "routed": true
                },
                "text": "Health services"
            },
            {
                "url": {
                    "path": "",
                    "routed": true
                },
                "text": "Patient advocates"
            }
        ],
        "path": "\/pittsburgh-health-care\/patient-advocates"
    }
```

**Comment by jhonnyoddball** [comment]
This issue was fixed!
