### ISSUE TITLE
Content builds result in some file links showing internal domain.

### ISSUE THREAD

**Issue by swirtSJW** [department-of-veterans-affairs/va.gov-team#13455]
Visit: https://www.va.gov/pittsburgh-health-care/events/introduction-to-whole-health/

![image](https://user-images.githubusercontent.com/1504756/85179710-79395500-b236-11ea-8cd7-808a8f47a4ce.png)

Inspect liink "Link to Poster"   See that it points to http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com/sites/default/files/2020-06/MAP%20Monday%20V7.pdf

That domain is an internal domain that does not resolve unless you are in the VA network or on SOCKS.

Two possible solutions:
1:  Alter the URL rewriting  logic to get catch the file URLs in the "processed" properties within pages.json.
Here?? https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/stages/build/drupal/assets.js#L76-L103
 Added 9/22:  LOE I think is pretty low.   It is just an additional pattern added to the host replacement pattern (find and replace). As in, when it finds something like this
http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com/sites/default/files/2020-06/MAP%20Monday%20V7.pdf
remove the http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com
The only part that makes it a wee challenge is that 2000800896` is dynamic so a bit of regex is needed.

2. Make the CMS data request to https://prod.cms.gov rather than http://internal-dsva-vagov-prod-cms-2000800896.us-gov-west-1.elb.amazonaws.com   (@cvalarida  has already tested and confirmed that this worked).
https://github.com/department-of-veterans-affairs/vets-website/blob/master/src/site/constants/drupals.js#L53

**Comment by ElijahLynn** [comment]
> can we migrate this issue to https://github.com/department-of-veterans-affairs/va.gov-team? we don't use vets-website repo for tracking issues.

Done :heavy_check_mark:

**Comment by swirtSJW** [comment]
New set of cases where this is still an issue.    There are a pair of broken links on prod, but they are not being caught during link checking because they are accessible from the VA network... BUT only from the VA network.
https://www.va.gov/pittsburgh-health-care/stories/free-flu-shots-for-veterans/


![image](https://user-images.githubusercontent.com/5752113/93649621-67ed1980-f9da-11ea-99e8-0e34ff020a53.png)

**Comment by ElijahLynn** [comment]
Hrm, seems like maybe we should do a scan on all the output for `http.*internal.*` links as a build step too.

**Comment by timwright12** [comment]
@swirtSJW I just saw this on our board, is it still an open problem?

**Comment by ElijahLynn** [comment]
> @swirtSJW I just saw this on our board, is it still an open problem?

I think it was never addressed. The issue was mitigated by changing the links that were entered in the CMS. If another link is entered like that I think it will break again.

**Comment by swirtSJW** [comment]
@timwright12 I believe this is still an issue.   As Elijah mentioned we altered the content to make it not be a current issue, but any editor could create this situation in the future so it makes sense to resolve this with a more permanent solution.

**Comment by kevwalsh** [comment]
See https://github.com/department-of-veterans-affairs/va.gov-cms/issues/3292 epic, which is another way to take care of this in the content layer, and with some drupal engineering. AFAIK, the only place this issue has shown up is when one editor has used the "Embed entity" tool in the rich text editor.

**Comment by swirtSJW** [comment]
That was one source... but  I think the potential exists for others.   Largely the problem is that the link checker either did not scan it because it thinks its an external link, which it is not, or it scanned it but determined it was good because the link checker runs as though it is within the VA network.

**Comment by ElijahLynn** [comment]
PR here now > https://github.com/department-of-veterans-affairs/content-build/pull/161.

**Comment by timwright12** [comment]
@ElijahLynn looks that PR got approved

**Comment by meganhkelley** [comment]
@ElijahLynn @swirtSJW Could y'all please let us know if there are remaining action items for FE Tools here? Thanks!

**Comment by swirtSJW** [comment]
Looks like even though the PR got approved, it was never merged and that the file src/site/stages/build/plugins/check-cms-urls.js  no longer exists in this repo.

To my knowledge, the issue has not appeared recently,  **but** it was the kind that occurs silently until someone complains.   We only discovered it by stumbling upon it.. I am not sure if this is resolved or just dormant until the next time it appears.

**Comment by rmessina1010** [comment]
@swirtSJW  is this the same, or related to, #28139?

**Comment by rmessina1010** [comment]
Expired. Closing.
