### ISSUE TITLE
[Bug] Campaign Landing Page - Content/styling anomalies

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#20629]
## What happened?
On CMS-prod-preview **[Campaign Landing Page](http://preview-prod.vfs.va.gov/preview?nodeId=16139)** draft, the following content/styling anomalies were found:
- In **Hero banner**, hero-image was missing.
- In **What you can do** & **Stories** sections, images were not displayed.
- In **Video**, **Stories**, **Events**, and **Connect** sections, light-blue backgrounds were missing.
- In **Downloadable resources** section, 3rd card, PDF download link was not bottom-aligned.  **NOTE**: On mobile screens, this anomaly was not apparent as the cards were variable-height.

## Specs:
- Device: [device-agnostic]
- Browser: [browser-agnostic]
- Test User _(if applicable)_: [n/a]

## Steps to Reproduce
- Go to http://preview-prod.vfs.va.gov/preview?nodeId=16139 [no login required]
- Observe content/styling anomalies listed above.

### Screenshot(s)

**Hero** banner - missing hero-image:
![clp-bug-hero-banner-missing-image](https://user-images.githubusercontent.com/587583/109574285-dc110a80-7aac-11eb-9648-34f1aae209e4.png)

**What you can do** - broken images:
![clp-bug-what-you-can-do-images-broken](https://user-images.githubusercontent.com/587583/109558312-7a45a600-7a96-11eb-8eb6-ceaa2de7682b.png)
[same anomaly also in **Stories** section]

**Video** section - missing light-blue background:
![clp-bug-alt-sections-missing-blue-bg](https://user-images.githubusercontent.com/587583/109559855-6f8c1080-7a98-11eb-91f9-f18d608f9735.png)
[same anomaly also in alternate subsequent sections (**Stories**, **Events**, **Connect**)]

**Downloadable resources** section - PDF-link not bottom-aligned:
![clp-bug-download-links-not-bottom-aligned](https://user-images.githubusercontent.com/587583/109574167-b2f07a00-7aac-11eb-8de6-400add0ce526.png)

## Desired content/styling
- [x] Hero-image should display properly.
- [x] Section images should display properly.
- [ ] ~~Alternate sections should have light-blue backgrounds.~~
- [x] PDF-links should be bottom-aligned.

[See [Design prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1607363793772/b7f9e809d68ace9c8d75ab649a758ed7653c8461)]

## Acceptance Criteria
- [ ] _Describe the desired working behavior_

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Attached to Epic** (what body of work is this a part of? possibly `Ongoing Maintenance`)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `contact center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by brianalloyd** [comment]
Checking with Ryan on styling.  PDF should be bottom aligned (FE Fix).

**Comment by tlei123** [comment]
@ncksllvn / @kelsonic , pls. be sure to tag me if you can't replicate the missing/broken images on the [preview-page](http://preview-prod.vfs.va.gov/preview?nodeId=16139).  I'm still not sure if it's just due to something wrong w/ my SOCKS-proxy config.

Thx much!  :)

**Comment by tlei123** [comment]
@ncksllvn @kelsonic , i just striked-out the broken-images item above for **What you can do** & **Stories** sections.  It turns out the images just didn't load for me -- see [this Slack thread](https://dsva.slack.com/archives/C01DS1XDEQ0/p1615228016088000).

**Comment by tlei123** [comment]
@ncksllvn @kelsonic , the [preview-page](http://preview-prod.vfs.va.gov/preview?nodeId=16139) images are now loading for me.  At first I thought they loaded just 'cuz I logged into prod.cms.va.gov [where those missing images are from], but today I'm logged out and the images are still loading on the preview-page.  So, the problem seems to have fixed itself!  :D

**Comment by brianalloyd** [comment]
@tlei123 looking over this ticket I believe all the actions have been resolved.  Could you advise on any remaining actions that are needed and we'll action soonest.  Thanks.

**Comment by tlei123** [comment]
@brianalloyd , I just did a quick check in Mac Chrome...

All items resolved EXCEPT light-blue backgrounds are still missing in Video & subsequent-alternating sections. [See [prototype](https://app.mural.co/t/departmentofveteransaffairs9999/m/departmentofveteransaffairs9999/1607363793772/b7f9e809d68ace9c8d75ab649a758ed7653c8461)]

Let me know when that remaining item's fixed, then I'll check desktop, phone, & tablet screens.  Thanks much!  :)

**Comment by brianalloyd** [comment]
@tlei123 thanks for circling back, the background variant was a design change from @rtwell and @johnhashva based on internal UAT that determined if a user only selected the 4x required panels then the staggering backgrounds wouldn't align correctly.  That change is what is now being reflected on the FE styling.  Let me know if you have any questions.  Thanks.

**Comment by tlei123** [comment]
@rtwell , please provide link to your updated design for all-white-backgrounds [see Brian's comment above].

Thx much!

**Comment by tlei123** [comment]
@brianalloyd , follow-up test-runs completed - 100% passed.

Once I have link to updated design prototype, I'll update my test-case and Close this ticket.

**Comment by brianalloyd** [comment]
Sounds great, thanks again @tlei123 appreciate the follow up and support on this product.

**Comment by johnhashva** [comment]
@tlei123 + @rtwell  + @brianalloyd  -- in the event that a design is not readily available, how about a link to (or screenshot of) the live prototype in CMS Preview?  http://preview-prod.vfs.va.gov/preview?nodeId=16139.

**Comment by rtwell** [comment]
1. The spacing between images and headers in the "WHAT YOU CAN DO" section are too large—they should mirror the spacing in the other cards:
![image](https://user-images.githubusercontent.com/12564977/111634210-ac604300-87cc-11eb-9dbd-21caa2fc1f7a.png)

2. updated comp (although i think the spacing @kelsonic has per-section is perfect:

![image](https://user-images.githubusercontent.com/12564977/111633664-20e6b200-87cc-11eb-98da-17003720c64c.png)

**Comment by brianalloyd** [comment]
Thanks @rtwell for the updated specs and the call out on spacing between images and headers in the "WHAT YOU CAN DO" section.  PW Team will scrub in on this issue today in support.

**Comment by rtwell** [comment]
no prob—i want to say i pointed this out in another issue, but idk where it is 😢

**Comment by tlei123** [comment]
> ...in the event that a design is not readily available, how about a link to (or screenshot of) the live prototype in CMS Preview? http://preview-prod.vfs.va.gov/preview?nodeId=16139.

@johnhashva , fyi for future reference...  Sorry, no, not for QA purposes.  Requirements need to be separately documented for QA.  Providing a screenshot of the page-under-test as a design reference for QA'ing the page-under-test means QA's always gonna pass.

**Comment by tlei123** [comment]
> 2\. updated comp (although i think the spacing @kelsonic has per-section is perfect:

@rtwell , pls. give me the **link** to your updated comp.  Thx much!
