### ISSUE TITLE
Adding Daniel Fein to DSVA Slack

### ISSUE THREAD

**Issue by dfein-rpg** [department-of-veterans-affairs/va.gov-team#30898]
# Description

**new user requests**: please verify that the user does not already exist in dsva.slack.com (it may be the account exists, but is not in a particular channel)

The following guest user daniel.fein@va.gov should be switched from single-channel to multi-channel guest and then added to vfs-platform-support

Are you requesting to add an individual as a:

- Full member
- Single guest
- Multi-channel
- Switching from single-channel to multi-channel? **Yes**
- What channel(s) do they need to be added to?  **vfs-platform-support**

Then add a brief description of this person, their role on the project, and why they should be added under the status you have requested.
I am a data scientist on the VBA Fraud Prevention Services Team. We are working to gain access to Grafana/Loki to support our fraud prevention analytics efforts. We have been working closely with developers on the va.gov team who have instructed us to obtain access to the above channel for support. 

We aim to complete slack requests within 24hrs.

## Sample Descriptions 
- Please add [_insert email_] as a single-channel guest to [_channel name_].
- Please add [_insert email_] as a multi-channel guest to these channels: [_channel names_].
- Please add [_insert email_] as a full member.
- Please change the status of [_slack username_] from [_current status_] to [_desired status_]

**Comment by LizCallaghan** [comment]
done!

**Comment by dfein-rpg** [comment]
@LizCallaghan Thanks so much for the quick turn around! How long will it take for these changes to take effect? As of right now I'm still showing as Single-Channel Guest and do not have access to the vfs-platform-support channel.

**Comment by LizCallaghan** [comment]
should be updated now, thanks for catching that!
