### ISSUE TITLE
[FE] My VA - Health Care section: Update Next Appointment connection

### ISSUE THREAD

**Issue by ajakabcin** [department-of-veterans-affairs/va.gov-team#40115]
## Background
Per [slack convo](https://dsva.slack.com/archives/CMNQT72LX/p1649855859476399) last week, VAOS is in the process of updating its endpoints which means we need to make some updates on our side so that we are pulling from the correct/most update to date service. We need to connect to V2 instead of V0.

### Resources:
- [V0 documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v0/vaos.yaml)
- [V2 documentation](https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/vaos/app/docs/vaos/v2/vaos_v2.yaml)

_NOTE: VAOS has not launched V2 to production. It's currently in staging so we'll need to gate this so as not to go prod before VAOS sends V2 to prod._

## Tasks
- [x] Review documentation to see what changes need to made
- [ ] Make changes (if additional tickets are needed work with PM/APM)
     - [x] Gate
     - [x] v2 implementation
     - [ ] test

## Acceptance Criteria
- Service is updated (gated)
- Applicable FE documentation is updated

**Comment by ajakabcin** [comment]
hey @mdewey - want to make sure you're not stuck here. Getting the info you need? Thanks?

**Comment by mdewey** [comment]
Hey! @ajakabcin I have some of my questions answered.I am going to revisit this today with the answers I have and see if I am missing anything else. 

One question I have for you: Do we have a wireframe/mockup/sketch/mural for this feature? I am trying to work out the edge cases and that would help see what is what.

**Comment by ajakabcin** [comment]
Looping in @aagosto90 to get you the info you need!

**Comment by aagosto90** [comment]
@mdewey Here's a link to our [product guide](https://docs.google.com/document/d/1PQesXzT3WIMrUWA4HXVnKyI3kEn9izuIM2XPJy_vUdc/edit) - if you go to page 22 that's where the health care section starts. Let me know if anything is confusing or if you need links to the Sketch file! I think this doc will do the best job of explaining the different scenarios and what we show for each.

**Comment by mdewey** [comment]
@aagosto90 I need access to that product guide

**Comment by aagosto90** [comment]
@mdewey Sorry about that - I just granted you access

**Comment by mdewey** [comment]
What email did you use? I am still having access issues :-( 

My google account is mark.dewey.gcio.@gmail.com

**Comment by ajakabcin** [comment]
@mdewey you can also find the product [here](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/identity-personalization/my-va/product/product-guides.md) - all versions available. The one Angela is sharing is version 3.

**Comment by mdewey** [comment]
I was able to test this in staging. I got the following results: 
![Screen Shot 2022-05-04 at 11 00 16 AM](https://user-images.githubusercontent.com/1793923/166712165-62ef764c-4d6f-42ad-a278-78073c1ca443.png)

two errors where found: 
- The time is different. At this point I am not sure if the data is different or if there is something wrong with the logic. I am digging into this
-  The loading message doesn't appear with the `v2` implementation. This will need fixed.

**Comment by Samara-Strauss** [comment]
Thank you for the update, @mdewey!! Let me know what you find, and I can take a look once you've got these issues ironed out.

**Comment by mdewey** [comment]
Hey @Samara-Strauss  and @ajakabcin!

After a PR and some digging, this looks good to test. The loader is fixed and it looks like the data being returned is different in the two endpoints. 

I still have one outstanding question (https://dsva.slack.com/archives/C909ZG2BB/p1651670264192099). 

From my perspective, I am done with the first pass of dev work. This is ready to be tested and validated. I will enable this in staging and await feedback (that should go into their ticket 🤷  )

**Comment by Samara-Strauss** [comment]
Hey @mdewey! I validated that I can still see appointments with Judy.Morrison. However, I noticed that I see the "no appointments" state before the appoint state appears for maybe 5 seconds:

![image](https://user-images.githubusercontent.com/34068740/166813350-f98e185c-9a67-4b66-8a32-daf67e451994.png)

Before finally seeing this:

![image](https://user-images.githubusercontent.com/34068740/166813730-be4b764d-c7da-48f5-94e4-9b7877c00996.png)

Is there anything we can do to prevent this, or is this just something that's gonna happen until the content loads?

**Comment by mdewey** [comment]
@Samara-Strauss I think you just missed the fix for the loader.
![loader](https://user-images.githubusercontent.com/1793923/167482153-b822dfb0-5c09-4015-a344-14794d0aca4f.gif)

The loader is fixed.

**Comment by ajakabcin** [comment]
Heard back from VAOs - they are looking to make the transition to prod by the end of this month (May), they have a few outstanding issues remaining. I will follow up with them next week ahead of our sprint planning to see where they are to see if there is anything needed from us for the transition other than communication. Slack thread [here](https://dsva.slack.com/archives/CMNQT72LX/p1652193324556079) for reference.

**Comment by Samara-Strauss** [comment]
Great! Question for Mark -- is this behind the same feature flag as the larger VAOS V2 code, or a different flag? If it's the same flag, I assume this will just go out with the larger VAOS work. If it's a different flag, we have a couple options:

1. Close this ticket, and open a new one for us to launch this work when it's ready.
2. Keep this ticket open and use this ticket to track launching this work. For sprint reporting purposes, however, we can consider this work complete.

**Comment by ajakabcin** [comment]
My $0.02 - I say we close this and have a separate ticket to capture any/all work for launching with VAOS. If we need to create a feature flag for this I'd say a new ticket for that as well.

**Comment by mdewey** [comment]
This ticket is behind our own feature flag. So we can go on our timetable. 

I second closing this ticket and creating a new one for launch. The initial work is done, now it's launching and validating, and fixing any potential issues that come up. And those should be their own ticket.

**Comment by Samara-Strauss** [comment]
All of this sounds good to me! Thanks!

**Comment by ajakabcin** [comment]
Created #41202 - closing this. Thank you @mdewey !
