### ISSUE TITLE
TeamSite doc for devops changes is out of date

### ISSUE THREAD

**Issue by jilladams** [department-of-veterans-affairs/va.gov-team#43364]
### Description
Instructions for devops allow lists reference outdated code: The commit examples linked from https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview#TeamSiteoverview-Considerationswheneditingandtestingtheallowlist are pointing at a commit hash version of the file. Links from that doc =

https://github.com/department-of-veterans-affairs/devops/blob/c5687fc1b483eaea17a1191eb41440fb560d01d6/terraform/environments/dsva-vagov-prod/main.tf#L277
https://github.com/department-of-veterans-affairs/devops/blob/c5687fc1b483eaea17a1191eb41440fb560d01d6/terraform/environments/dsva-vagov-prod/main.tf#L290

That code has been significantly refactored in master. 

TeamSite CORS allowed origins for `bucket-prod-va-gov-assets` and `bucket-preview-va-gov-assets` are now part of the vets-api module, so docs should instead point to https://github.com/department-of-veterans-affairs/devops/blob/master/terraform/environments/dsva-vagov-prod/main.tf#L274 in `master` branch, and instruct users to add new domains to `local allowed_origins`.

**Comment by laucon** [comment]
I believe that all of this has been resolved on the document, [TeamSite overview](https://depo-platform-documentation.scrollhelp.site/developer-docs/teamsite-overview), and I _think_ that this ticket can be closed.

**Comment by jilladams** [comment]
Hi @laucon  - I found one place the Allowlist link is still incorrect in the docs: in this paragraph: 

`There are an unknown number of TeamSite templates that drive the <head> content on TeamSite pages and there are several pages that receive the above markup that should not show the VA.gov header. The proxy rewrite application uses a [allowlist](https://github.com/department-of-veterans-affairs/vets-website/blob/b770f380270722228563e56629af440c64342157/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json) to drive the activation of the header content. Example allowlist entry:`

That URL should be: https://github.com/department-of-veterans-affairs/vets-website/blob/main/src/applications/proxy-rewrite/proxy-rewrite-whitelist.json

Otherwise, looks good! Thank you for getting this handled.

**Comment by laucon** [comment]
Thanks! I'll create a new ticket to fix this and try and get this done ASAP.

**Comment by jilladams** [comment]
Sounds good!
