### ISSUE TITLE
PROD AND STAGING:  Mental Health Clinic Display Issue:  Veterans w/No past MH Appts

### ISSUE THREAD

**Issue by marcynadeau** [department-of-veterans-affairs/va.gov-team#44069]
Two preconditions for this issue to occur:
1.  User must navigate through a flow for another type of specialty care before selecting Mental Health
2.  User must NOT have any past Mental Health Appts within the last 36 mos.  
3.   Reviewed with dev team and this is a medium to low priority issue due to:  1) Vet will be dropped into request flow 2) This only affects vets without past MH appts 3) If Vet chose MH first and not another type of care this issue would not present 4) If vets refreshes pages or logs out and logs back in MH clinics would then displays.  

**Steps to to recreate:**
1. Login Select Type of care, select Mental Health, select Cheyenne. The following displays: Would you like to make an appointment at CHY MENTAL HEALTH ONE?(*Required). Yes, make my appointment here. No, I need a different clinic.
2. From the breadcrumbs navigate to Home Page.
3. Select type of care (other than Mental Health), if prompted Select VA facility. Select location. Several things could happen here: 1) Modal window displays with an explanation of why further action can't be taken OR 2) Vet dropped into Request flow OR 3) Vet dropped into Direct scheduling flow.
4. If modal window displays, close the modal and use the breadcrumbs to navigate back to home page. OR you can continue through the Request flow or Direct Scheduling flow OR you can use the breadcrumbs to navigate to Home page. What action you do at this point does NOT matter.
5. Navigate back on the Home page, select Mental Health.  Select Cheyenne.
6. System displays: Choose a clinic below or request a different clinic for this appointment.(*Required):  I need a different clinic
7. Expected Response:  Would you like to make an appointment at CHY MENTAL HEALTH ONE?(*Required). Yes, make my appointment here. No, I need a different clinic.
8. Actual Response:   Choose a clinic below or request a different clinic for this appointment.(*Required):  I need a different clinic

**To test this I used this patient:** john.morrison@id.me (for retesting you will need to verify that after I logged the defect that no one added MH appts for this patient.     I had Jenny McGibney temporarily move this patient to VAR-Resources.  

[https://app.zenhub.com/files/133843125/eca4ee5b-49f5-464a-9f40-f666a50ca167/download](https://app.zenhub.com/f iles/133843125/eca4ee5b-49f5-464a-9f40-f666a50ca167/download)

![MHClinicIssue.png](https://images.zenhubusercontent.com/5f2d82e4a65f7435058cfd75/b8b84d93-9ecc-42e6-bed2-da16b642e632)

**Comment by marcynadeau** [comment]
Leah reached out to me to verify if this is still an issue. Contacted Beth via Slack and she will be testing this with the patient in the referenced in the defect in VAOS service and then VAR-Res.

**Comment by beth-wodzinski** [comment]
This worked as expected last night. Today we switched the test patient (john.morrison@id.me) to VAR RES and it no longer worked, which Marcy expected. Then we switched the patient back to VAOS service and it still doesn't work.

**Comment by ldelacosta** [comment]
@vbahinwillit - Please put the code behind the feature toggle for vaos-v2-next #44559.

**Comment by vbahinwillit** [comment]
Done.

**Comment by ldelacosta** [comment]
@marcynadeau - This ticket is ready to be tested. Thanks!

**Comment by beth-wodzinski** [comment]
This failed testing. I followed the steps above, and at Step 6, I still see this ![image.png](https://images.zenhubusercontent.com/5f2d82cd1166696dbe88379c/dd92c5fd-f8ce-4e83-bac2-111c3728f2ec)

@ldelacosta

**Comment by beth-wodzinski** [comment]
note: this worked as expected on VAR RES patient Ruben Moreno, but did not work on VAOS SERVICES patient John Morrison.

**Comment by ldelacosta** [comment]
@vbahinwillit - Could you please take a look at Beth's comments and advise?

**Comment by ldelacosta** [comment]
@beth-wodzinski - V2next feature toggle was turned off. Can you please re-test in staging and see if it's working? Thanks!

**Comment by beth-wodzinski** [comment]
This passed testing with both Var Res and Vaos Service. @ldelacosta

**Comment by ldelacosta** [comment]
No issues reported. Closing out the ticket.
