### ISSUE TITLE
[Bug] Facility Locator - Map-icon displays incorrect location-popup when close to or overlapped by another icon

### ISSUE THREAD

**Issue by tlei123** [department-of-veterans-affairs/va.gov-team#4764]
## What happened?
On Staging Facility Locator page, when the map shows two icons that are close together or overlapping, clicking on one of the icons brings up the other icon's location-popup.

The overlapping icon (or the one stacked on top) "hijacks" the click intended for the icon underneath.

## Specs:
- Device/Browser: [this bug is browser- and device-agnostic]

## Steps to Reproduce
1. Go to https://staging.va.gov/find-locations/
1. In **Search...** textbox, input **1600 Pennsylvania Ave NW, Washington, DC 20500**.
1. From **Search for** dropdown menu, choose **VA Health**.  IF you wait for more than 30 secs for results, refresh the page and results should then load.
1. In the **Map-panel**, click on the icon in the center [i.e., the icon of the two overlapping icon-pair in the center].
1. Observe that the **location-popup** that appears is for **Franklin Street VA Clinic**.
1. Now click on the icon that's underneath & slightly to the left of the Franklin-street icon.
1. Observe that the **location-popup** that appears is still for **Franklin Street VA Clinic**.
1. Click **+** button to zoom-in, and keep clicking until the two icons are separated at least by 25px.
1. Now click on the icon on the left.
1. Observe that now the **location-popup** is correctly for **Washington VA Medical Center**.

#### Wrong location-popup when clicked icon is close to or overlapped by another icon - Win Chrome example
![map-icons-overlap-1](https://user-images.githubusercontent.com/587583/72227389-4093a200-3559-11ea-9af0-4513651b6fbe.png)

#### Correct location-popup when clicked icon is clearly separated from others - Win Chrome example
![map-icons-overlap-2](https://user-images.githubusercontent.com/587583/72227421-8f413c00-3559-11ea-9a88-52d309bf967c.png)

## Desired behavior
Icon displays correct location-popup even when close to or overlapped by another icon.

## Acceptance Criteria
- [ ] \[see **Desired behavior** above]

## How to configure this issue
- [ ] **Attached to a Milestone** (when will this be completed?)
- [x] **Labeled with Team** (`product support`, `analytics-insights`, `operations`, `triage`, `tools-improvements`)
- [x] **Labeled with Practice Area** (`backend`, `frontend`, `devops`, `design`, `research`, `product`, `ia`, `qa`, `analytics`, `call center`, `research`, `accessibility`, `content`)
- [x] **Labeled with `Bug`**

**Comment by tlei123** [comment]
Juding from the separation required in replication Step 8 while zooming-in, I'm suspecting there's some margin styled around the icon-image that expanded the click-zone too far out beyond the visible icon.

**Comment by mmiddaugh** [comment]
This issue is resolved by UX changes which have removed pop-ups on the map.

**Comment by tlei123** [comment]
> This issue is resolved by UX changes which have removed pop-ups on the map.

@mmiddaugh , I'm assuming the upgrade you meant is not on Staging yet, which would explain why this still persists on Staging when I re-run my failed test-cases.

Just adding a Comment here for due diligence.
