### ISSUE TITLE
Analytics Implementation or QA Support for Benefits Team Download Decision Letter Feature

### ISSUE THREAD

**Issue by jacobworrell** [department-of-veterans-affairs/va.gov-team#47760]
# Google Analytics Implementation or QA Request

## What this form is for

<details>
<summary>More Information</summary>
<div>
    <br>
<p>Use this template to request Google Analytics implementation or QA for your product. Please fill out all brackets.</p>
    
> _Please see the following information for implementation timeline:_
> New Teams: Implementation will usually be completed in 4 sprints
> 
> - Sprint 1: Discovery/Orientation
> - Sprint 2: FE Implementation
> - Sprint 3: Tagging Implementation
> - Sprint 4: QA
> 
> All other teams: Implementation will usually be completed in 2 sprints
> 
> - Sprint 1: Discovery and FE Implementation
> - Sprint 2: Tagging Implementation and QA

</div>
</details>

### Required
- **Is this request for **Google Analytics implementation** or **QA**?**

     - [ ] Google Analytics implementation
     - [ ] QA

- **Who is this request for?**

    - [Insert team name(s), for individual's names please use the `/support` tracker on the #vfs-platform-support channel and link this ticket.]
    
    
- **Provide the link(s) for Google Analytics implementation or QA**
  
    - [Feature Outline](https://github.com/department-of-veterans-affairs/va.gov-team/blob/master/products/claim-appeal-status/CST%20Product/Decision%20Letter%20Feature%20Brief.md)
    - [Designs](https://www.sketch.com/s/8b025901-295d-4929-95cc-8dbeb28454b3/p/CAA1846C-79ED-4BDB-94B9-BA0EBE74EC5B/canvas)
    
- **When is the launch date?**
    Stage A Release Tentative Date: 11/16/2022

- **What interactions need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked_
    
    - va.gov > va.gov/claim-or-appeal-status/ > va.gov/track-claims/your-claims >va.gov/track-claims/your-claims/status > va.gov/track-claims/your-claim-letters
    - # of download links clicked
    - we would also like to suggest a new sub category for call center tracking. VA Benefits Letters already exists, but we'd like to add a "decision/notification letter" subcategory to it. 
    
    - [Insert other interactions - please review the [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) and [GA Data Dictionary](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Google-Analytics-Data-Dictionary.1810464912.html)  to make sure these interactions aren't already tracked]

### Optional
- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - We have already created our own test users in collab with VBA VBMS team members, we can provide those credential if needed. We  have no additional requests related to test users.

- **Any additional comments**

    - please let us know if anything critical is missing from this ticket.

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@jacobworrell - thank you for your submission.  We will review as part of grooming this week and get back to you with timing.

**Comment by jacobworrell** [comment]
@michelle-dooley any update on this. The feature is currently on production but hidden behind a feature flag.

**Comment by michelle-dooley** [comment]
@jacobworrell - I'm having trouble locating the exact pages.  Can you please send me the urls and screen shots of the pages with the download link you would like to track.  Could you also provide a test user that has this information so I can walk through it.

**Comment by jacobworrell** [comment]
@michelle-dooley test users are here: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/blob/master/Administrative/vagov-users/mvi-staging-cst-users.csv

URL path: va.gov > va.gov/claim-or-appeal-status/ > va.gov/track-claims/your-claims >va.gov/track-claims/your-claims/status > va.gov/track-claims/your-claim-letters

**Comment by michelle-dooley** [comment]
So these are the letters you want to track?  Is this the only page they can be accessed?
![image](https://user-images.githubusercontent.com/93597659/198709669-f2a93fd2-1452-4911-abb5-46791ac9f020.png)

**Comment by michelle-dooley** [comment]
@jacobworrell - this should give you what you need.  Let me know once you implement and we can test.

Event: 'claim-letters-download'
Prefix: 'claim-letters'

**Comment by jacobworrell** [comment]
Thanks @michelle-dooley!

@jerekshoe please see above.

**Comment by michelle-dooley** [comment]
@jacobworrell - just following up, have you added the code yet?  If not when do you expect to?  I may move this to ice box depending on your timing for that.  Then after you complete we can QA.

**Comment by jerekshoe** [comment]
@michelle-dooley I apologize for the late reply, but I just put a PR out to implement this. I will follow up again here after it is in staging

**Comment by jerekshoe** [comment]
@michelle-dooley Just a heads up, the event should be set up in staging, and should be pushed to prod later this afternoon

**Comment by michelle-dooley** [comment]
@jerekshoe - I see that the download event is tracking now but it doesn't seem to be mapping all the label details (see below).  You can see the "Downloaded" event in the console and in GA report but it is not coming over with the "PDF" prefix or the "click text" in the event action as expected but you do see the URL so not sure if that will suffice or not....

![image](https://user-images.githubusercontent.com/93597659/202560636-100de644-d6f1-4b09-aaa5-aa7dca966586.png)

![image](https://user-images.githubusercontent.com/93597659/202560441-dcf25036-e717-44e6-b70d-41bb74a8b7d6.png)

![image](https://user-images.githubusercontent.com/93597659/202559993-6e6db9e6-6bd5-4b20-8004-def072c24fcd.png)

![image](https://user-images.githubusercontent.com/93597659/202560167-e6eed391-3f08-4f21-9f43-b58984e6beba.png)

**Comment by jerekshoe** [comment]
@michelle-dooley Can you check this again? I updated the code in a way that I think will now show: `Downloaded - Download letter (PDF)`. I'd like to verify this assumption and see if this worked the way I expected

**Comment by michelle-dooley** [comment]
@jerekshoe - Still not seeing it.  I figured out the issue though.  The url does not have a pdf extension which triggers the event action look up table and would add the PDF in front of "Downloaded".  See screen shots below of a different download event that is tracking as expected.  Not sure why the "click text" isn't coming through though?!?
![image](https://user-images.githubusercontent.com/93597659/204868405-0dbf4d06-c612-43e2-84c8-258cfe522cab.png)

![image](https://user-images.githubusercontent.com/93597659/204868527-34a3e609-d0fc-4ac1-8c30-5e4e3e159e55.png)

**Comment by jerekshoe** [comment]
Hey @michelle-dooley the extension not existing is expected behavior as we are not getting the PDFs from a static location and instead are generating on the backend. The analytics events that you are seeing, are these in Production (va.gov) or can you see staging as well (staging.va.gov)? I am sending this object as part of the GA event now, so I was hoping that the click text would work, but if you are only looking at production events then it could be not showing 
because users don't have access to this page in production and I don't think anyone has tested it in a while on va.gov.
```js
recordEvent({
  event: 'claim-letters-download',
  'click-text': 'Download letter (PDF)',
});
```

**Comment by michelle-dooley** [comment]
@jerekshoe - I am testing in staging.va.gov

**Comment by michelle-dooley** [comment]
@jerekshoe - just following up on this.  Do you have what you need or are you still working on this?

**Comment by jerekshoe** [comment]
@michelle-dooley sorry I had meant to follow up but had forgotten to until now. Is there anyway to set the Click Text programatically? I think the reason it doesn't show up is because the link uses a web component so if it's possible to set the Click Text in some other way that would be helpful. Other than that I think that we are good to go on our end

**Comment by michelle-dooley** [comment]
@jerekshoe - what web component does it use?  I think click text can be dynamically populated from the click label in the urll/href code?  I'll be honest this is where the disconnect comes for me.  Are you populating any other events with the click text?  Do you know any other FEs that may be able to explain how they do?  I'm sorry this is not my area of expertise and the resources on our team that were experts are no longer with us so I am trying to navigate through but it is a bit of a challenge.

**Comment by jerekshoe** [comment]
From looking through the codebase for vets-website, I was able to find one instance where someone was setting the `click-text` variable as part of the event sent to GA. We are using the `va-link` web component like this:
```jsx
<va-link
        download
        filename={filename}
        filetype="PDF"
        href={downloadUrl(letter.documentId)}
        onClick={downloadHandler}
        text={`Download ${formattedDate} letter`}
      />
```

**Comment by jerekshoe** [comment]
I can ask some other FEs after the new year and see if they have any insights. I don't have much knowledge on working with GA either, so your help is immensely appreciated!

**Comment by jerekshoe** [comment]
It's possible that the fact that the text is dynamically interpreted may cause trouble, I can try seeing if creating the label different helps
