### ISSUE TITLE
Appointment List Redesign - Remove truncation from mobile view 

### ISSUE THREAD

**Issue by ldelacosta** [department-of-veterans-affairs/va.gov-team#54917]
## Description
Product and Design team are looking to update the appointment list to help the Veteran better understand the details for their appointment. Currently, the truncated text on the mobile view does not allow Veterans to read important information up front. Removing the truncation to display the entirety of the text on mobile view will allow Veterans to read the needed information without needing to open details pages. 

Image below is of the mobile appointment list with truncation
<img width="502" alt="Screenshot 2023-03-13 at 11 45 31 AM" src="https://user-images.githubusercontent.com/92750161/224799769-6764493e-9aaf-4690-bee9-f9504352b9cd.png">
---

## Acceptance Criteria
Background: the `va_online_scheduling_appointment_list` toggle is on

- [x] Remove truncation from mobile view. 

### Design Assets
[Design Spec](https://www.figma.com/file/JpGM8LGBCqAlL8qh3DmFk8/Home-Page-Redesign?node-id=4057%3A105122&t=zGLXSb9rUEF1Gt4l-1)

## Definition of Done
- [x] All acceptance criteria are met
- [x] Documentation is updated

**Comment by Cieramaddox** [comment]
@ldelacosta @outerpress Design spec added

**Comment by Cieramaddox** [comment]
@simiadebowale @ldelacosta Looks like truncation was successfully removed for mobile, but has also been removed for tablet and desktop as well.

**Comment by simiadebowale** [comment]
@Cieramaddox - do you mind taking a screenshot and test user details for truncation on desktop. I don't see any truncation with the users I tested with.

**Comment by simiadebowale** [comment]
@Cieramaddox - Pushing a fix for this now

**Comment by simiadebowale** [comment]
@Cieramaddox - please check back in a half hour. I just merged the PR. Waiting for it to get deployed.

**Comment by Cieramaddox** [comment]
@simiadebowale Sweet! Truncation came back to both desktop and tablet for upcoming appointments. I'm still seeing text wrapping for both pending and past appointments.

**Comment by ldelacosta** [comment]
@simiadebowale - could you advise on the comment from Ciera?

**Comment by simiadebowale** [comment]
Per my conversation with Ciera, 481px and below should have wrapped text. 481px and above should be truncated. 
Also, moving forward, we will be using the breakpoints provided by the design system team [here](https://design.va.gov/foundation/breakpoints)
We will make the required update.
cc: @ldelacosta @Cieramaddox

**Comment by vbahinwillit** [comment]
We need to talk about this more. The 481 break point is weird. If you set a static width for the truncation, everything is good at the small size. However,  as you resize the screen up to the next breakpoint of 768, there is more than enough room to display the text but it will not be shown due to the static size.

**Comment by vbahinwillit** [comment]
Please verify if #54818 fixed this.

**Comment by outerpress** [comment]
@vbahinwillit we'll still want to remove truncation from mobile views only. At the smallest sizes the text gets cut off too much. 

Larger sizes can keep truncation and the spacing overall is looking great.

**Comment by outerpress** [comment]
Yep @vbahinwillit in the design spec it shows what the mobile screen would look like without truncation/with text wrapping (it's the one on the right). Let us know if any other details would be helpful

FYI @Cieramaddox

**Comment by ldelacosta** [comment]
@Cieramaddox @outerpress - this ticket is ready to be validated in staging. Please let us know if you have any issues. Thanks!

**Comment by outerpress** [comment]
@ldelacosta looks good! I see no mobile truncation on pending, past, upcoming, as expected. And all other screen sizes are truncated as expected.

**Comment by ldelacosta** [comment]
No new issues. Closing out the ticket.
