### ISSUE TITLE
Analytics Implementation or QA Support for [Virtual Agent Chatbot - Prescriptions Management Feature]

### ISSUE THREAD

**Issue by alexperson-tw** [department-of-veterans-affairs/va.gov-team#72863]
### Description:
This ticket is to implement GA tracking with the Chatbot Product. This has been a topic of our Analtytics _Office Hours_, for the last couple of weeks, and we are planning to finalize this tracking officially in this sprint - will be a relatively small/manageable effort.

### Please provide the following details for this request
**Google Analytics Implementation Request**
- **Team Name**

    - Virtual Agent Chatbot Team

- **Product Name**

    - Chatbot
      
- **When is the launch date?**
    - The product is live on https://www.va.gov/contact-us/virtual-agent/

- **Provide the link(s) for Product/Page urls**
  
    - https://www.va.gov/contact-us/virtual-agent/

- **What Events need to be tracked?** _NOTE: [Design System Components](https://depo-platform-documentation.scrollhelp.site/analytics-monitoring/Design-System-Components.1840808040.html) are automatically tracked and should be used whenever possible to avoid custom configuration_

    - **Sessions successfully signed into our prescriptions management feature**
        1. Clicking `start chat` on the chatbot
        2. Type in trigger phrase "prescriptions"
        3. Click "yes" and sign in with Id.me test user
        4. User receives message "You are now in the Prescriptions Bot, where you can view, refill, and track your active VA prescriptions." and should be counted as one session

    - **Unique users who successfully signed into our prescriptions management feature**

    - **Redirects to MyHealtheVet after clicking a link displayed in a message from our chatbot**
        - After signing into the prescriptions feature, the second message received has a link to [My HealtheVet](https://www.myhealth.va.gov/mhv-portal-web/home). We would like to track anytime this link is used.
        - <img width="403" alt="Screenshot 2024-01-04 at 4 15 20 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/8857e943-9c17-4b51-adc9-b0d84f974224">
    
    - **Any button that is clicked from within the prescriptions feature**
        - At this point, this includes any buttons from the main menu.
        - <img width="379" alt="Screenshot 2024-01-04 at 4 20 23 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/2c9b12b3-b1e4-44af-85a7-9321a5848e96">
        
        - This also includes the "Yes", "No", "Next" and "Menu" buttons presented after the user clicks any main menu item
        - <img width="397" alt="Screenshot 2024-01-04 at 4 23 08 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/35c54e27-746a-4b58-975a-fb245c360809">

        - <img width="395" alt="Screenshot 2024-01-04 at 4 24 15 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/03bb34bf-970b-4ce7-acea-3d2f536441b2">

    - **Clicks on microphone icon to activate voice input after signing into prescriptions feature**
        - Before signing into prescriptions, the send button is displayed with a paper airplane. 
        - <img width="397" alt="Screenshot 2024-01-04 at 4 11 40 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/560bd241-fa6f-4f77-aa66-83c438d8a99f">

        - After signing into prescriptions, the send button is displayed with a paper airplane.
        - <img width="399" alt="Screenshot 2024-01-04 at 4 13 34 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/afd345be-3f67-4875-8922-5163874b6a07">

        - We would like to track whenever the voice input is enabled (indicated by the icon changing to the color red)
        - <img width="396" alt="Screenshot 2024-01-04 at 4 17 49 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/62622249/7b567e83-854d-4bc9-aed7-0bb7bbe7f47e">

- **If applicable, what test users are needed?**  _NOTE: Do not put staging credentials in this ticket; store or reference them in a .md file in the `va.gov-team-sensitive` repository_

    - [Insert test user]

- **Any additional comments**

    - [Insert comments]

> Please leave the following blank

## Acceptance criteria
- [ ] All appropriate issue tagging is completed
- [ ] QA has been completed
- [ ] Events have been added to `Product` and `Benefit Hub` Content Groups

## Additional information

Please refer to [Platform Collaboration Cycle](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/index.html) or the [Analytics Request Touchpoint](https://depo-platform-documentation.scrollhelp.site/collaboration-cycle/Analytics-request.1782120453.html) on Platform website for more information about the Collaboration Cycle.

**Comment by michelle-dooley** [comment]
@alexperson-tw the team will review and get back to you with timing.

**Comment by jestutt** [comment]
@alexperson-tw We spoke yesterday on the "login" api that measures when the chat connects to the prescriptions feature and I believe we said to go with what you and @szarrougtw thought best for the event name. 

For the **text link clicks**, there's already an event in place for those: 
```
'event': 'chatbot-resource-link-click'
'link': //populate with link click text
'linkText': //populate with link click URL
```

For the button clicks, the event template looks like: 
```
'event': 'chatbot-button-click'
'click_text': //populate with button click text
'topic': //populate with chatbox skill/topic/feature
```

- Note that I changed the event name from what was used for the decision letters to start with "chatbot" instead of "cta". No need to change the other but I think it's a good thing to start all chatbot events with "chatbot" moving forward. 
- Also, I added the second parameter as a way to add context with the "yes", "no", "next" buttons if desired. It is optional. 

For the microphone activation clicks, the event template looks like: 
```
'event': 'chatbot-microphone-enable'
```

- Just the event name should be enough for this event. 

Please let me know when all the events are in place so I can QA the GTM side of the implementation.

**Comment by alexperson-tw** [comment]
@jestutt 

### Questions:

For button clicks, is it mandatory to send the topic attribute with the chatbot-button-click events? We are able to easily tell from the front-end when we are in the prescriptions skill, however not when we are in other skills. 

If it is not a mandatory field, when a button is clicked within the prescriptions feature, would like to send the following event:
```
recordEvent({
        event: 'chatbot-button-click',
        click_text: buttonText,
        topic: 'prescriptions',
      });
```

When a button is clicked outside of prescriptions, we would like to send the following event:
```
recordEvent({
        event: 'chatbot-button-click',
        click_text: buttonText,
      });
```

Regarding microphone tracking, we found a way to differentiate when the microphone button is clicked to enable it vs. disable it. 
We would like to send a `chatbot-microphone-enable` event like you suggested when clicked to enable and a `chatbot-microphone-disable` event when the microphone is clicked to disable it. Is this possible?

**Comment by jestutt** [comment]
@alexperson-tw  As mentioned before, the `topic` parameter was included because "yes", "no" and "next" are generic enough that they may be used in multiple skills, even if they aren't yet. It's also **optional** so you don't have to use it if you think it's not needed. 

For the microphone status events, both would only fire on a click interaction? There won't be a `chatbot-microphone-disable` event fired when the chat tool loads for a logged-in user? Unless there's a strong argument for an on-load event, we should stick to the direct interaction event.

**Comment by alexperson-tw** [comment]
@jestutt - We have just opened a [PR here with our vets-website changes](https://github.com/department-of-veterans-affairs/vets-website/pull/27596). I will let you know when it is merged and deployed.

**Comment by alexperson-tw** [comment]
@jestutt - After reviewing the [vets-website deployment process](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployments), I realized that if I merge the PR to master there is nothing stopping the code from being deployed automatically to production at 3PM ET, potentially before the analytics team has time to test in a lower environment. Do I need to a feature toggle for these changes or do you know of an easier way to keep them from deploying to production automatically?

**Comment by jestutt** [comment]
@alexperson-tw   I know nothing about how the deployments work of how to keep something from being deployed. I can say that I don't think it will hurt anything if the code go into production right now. These are all new dataLayer events that you've added which need to be added to GTM before they can be sent to GA.

**Comment by alexperson-tw** [comment]
@jestutt - If you think it should be ok to deploy as is, that would be better from our perspective. Adding a feature toggle would involve more work on the current PR and also another PR being opened for vets-api. I don't _think_ there should be any problems promoting to prod either. In that case I'll go ahead and promote those changes now and proceed accordingly.

**Comment by alexperson-tw** [comment]
@jestutt - We have merged the changes to the main branch of vets-website ready for review. If I understand correctly, this automatically deployed the changes to dev and staging. The changes will be automatically promoted to production at 3PM EST tomorrow.

**Comment by jestutt** [comment]
@alexperson-tw  I'm not finding the `chatbot-button-click` event on dev and staging isn't connecting to the prescriptions skill when I tried today. Can you confirm that it was added? 

I also noticed that the `chatbot-microphone-enable` is firing multiple times on dev -- it almost looked like it fired once for each word I spoke when testing. I would think it would only fire when the activation interaction happens. 

On a separate note, you might have caught this already but I saw a typo in the first button yesterday -- "Active" not "Acitve"
<img width="490" alt="Screenshot 2024-02-05 at 12 22 12 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/c4b3ee8c-2803-4453-b8fa-823697c6d500">

**Comment by alexperson-tw** [comment]
@jestutt - Could you please elaborate on where you saw the typo on the button you mentioned today during office hours?

**Comment by jestutt** [comment]
@alexperson-tw  It's the first button in the first menu/button group that comes up after you enter "prescription" and the connection is made.

**Comment by alexperson-tw** [comment]
@jestutt - We have just merged a fix for the button tracking issue and changes should be available in dev by 2pm EST today ready for review.

Also, were you able to see the following event being fired after signing into the prescriptions skill through the chatbot?

```
recordEvent({
      event: 'api_call',
      'api-name': 'Enter Chatbot Rx Skill',
      'api-status': 'successful',
    });
```

**Comment by jestutt** [comment]
@alexperson-tw  Yes, the `api_call` event was firing on dev when we looked on Monday.

**Comment by jestutt** [comment]
@alexperson-tw  Can you confirm that the merge happened? It's 2:40 pm ET and I'm not still not seeing the `chatbot-button-click` event on dev. (Note that I used an incognito window so caching shouldn't be an issue.)

**Comment by alexperson-tw** [comment]
@jestutt - It looks like our commit was deployed into Dev (and higher envs) yesterday afternoon. How are you verifying that events are being sent when testing in Dev? We'd like a better way to test this than what we're currently doing, just logging to the console.

**Comment by jestutt** [comment]
@alexperson-tw  I tried to message you on Slack -- I use the browser's Inspect panel (Console tab) to confirm that the events are firing and visible in the dataLayer. I can show you how to do this with or without the Adswerve plug-in tool. I just need to know when you have 20 mins free fora Zoom or you can add something to my [calendar](https://calendar.google.com/calendar/u/0?cid=amFtaWUuc3R1dHRAb2RkYmFsbC5pbw).

**Comment by johnny-jesensky-adhoc** [comment]
This ticket will likely carry over to our next sprint.

@jwoodman5, as these implementation requests often involve frequent back and forth with other teams, I might experiment with finding more reliable ways to track our progress on these going forward. Timing on completion can be hard to predict, due to dependencies.

**Comment by alexperson-tw** [comment]
@jestutt - I've completed and merged the new solution for button click tracking. I confirmed from the console that the events appeared to be added to the dataLayer correctly and could see button click events along with the others. The code should be automatically deployed to Dev this afternoon at 2pm EST.

**Comment by jestutt** [comment]
@alexperson-tw  Tracking for all requested events has been published to production and non-production environments. You can find the events using the Event Action field as seen in the below screentshots (from testing interaction on dev.va.gov).

api_call
<img width="434" alt="Screenshot 2024-02-26 at 7 55 47 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/10984302-49c2-4db4-b024-44cc7b480b44">

chatbot-resource-link-click
<img width="600" alt="Screenshot 2024-02-26 at 8 04 27 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/a50ce2b8-ddd9-49b2-a9f8-519f3b627350">

chatbot-button-click
<img width="499" alt="Screenshot 2024-02-26 at 7 50 14 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/51abd00b-43ea-4209-b426-7cd48b7fcb28">

chatbot-microphone-enable
<img width="346" alt="Screenshot 2024-02-26 at 7 56 22 PM" src="https://github.com/department-of-veterans-affairs/va.gov-team/assets/141653184/79980f66-c181-4729-84cb-43b93cf93403">
