### ISSUE TITLE
Datadog: Verify submit and status counts

### ISSUE THREAD

**Issue by baltes** [department-of-veterans-affairs/va.gov-team#93659]
The video below shows submits for the past month in Prod for FMP enrollment. At the time of this writing, we should see 5 submits over two days. Since this is the FMP enrollment form, I don't think we should see multiple files per submit. We just need to understand why we see a missing PEGA status count of 10 for five submits.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlFCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34e8997b44a4e9735ad373a4f5368dcd5afcf546/Screen%20Recording%202024-09-25%20at%205.07.28%E2%80%AFPM.mov)

**Comment by cloudmagic80** [comment]
Resolved. The issue was with the query being set up to capture the last "last" count. Now the count is refreshed.

**Comment by baltes** [comment]
@cloudmagic80 I'm still not sure these numbers make sense. Looking at staging for the last month, there are records on the Missing PEGA Status List chart, but nothing in the Missing PEGA Status chart above it.
